---
version: '3'
services:
  connect:
    image: confluentinc/cp-kafka-connect:7.9.0
    hostname: connect
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      # Kafka Connect worker configuration
      CONNECT_BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: dataverse-connect-group
      
      # Confluent Cloud authentication
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_JAAS_CONFIG: ${SASL_JAAS_CONFIG}
      CONNECT_SASL_MECHANISM: PLAIN
      
      # Topic handling for Connect's internal topics
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_PARTITIONS: 1
      CONNECT_STATUS_STORAGE_PARTITIONS: 1
      
      # Auto topic creation
      CONNECT_TOPIC_CREATION_ENABLE: 'true'
      CONNECT_TOPIC_CREATION_DEFAULT_PARTITIONS: 1
      CONNECT_TOPIC_CREATION_DEFAULT_REPLICATION_FACTOR: 1
      
      # Converters for data format
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: ${SCHEMA_REGISTRY_API_KEY}:${SCHEMA_REGISTRY_API_SECRET}
      
      # Converters for internal data
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      
      # Other configurations
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/connectors"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      
      # Producer and consumer configurations for Confluent Cloud
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: ${SASL_JAAS_CONFIG}
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      
      # Producer configurations for topic creation
      CONNECT_PRODUCER_ENABLE_IDEMPOTENCE: 'false'
      CONNECT_PRODUCER_ACKS: 'all'
      CONNECT_PRODUCER_REQUEST_TIMEOUT_MS: '20000'
      CONNECT_PRODUCER_RETRY_BACKOFF_MS: '500'
      
      # Consumer configurations for Confluent Cloud
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: ${SASL_JAAS_CONFIG}
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      
    volumes:
      - ${FILE_PATH:-../../target/kafka-connect-dataverse-0.1.0-SNAPSHOT-jar-with-dependencies.jar}:/connectors/kafka-connect-dataverse.jar 